import { ImageResponse } from "next/og";
import { SITE } from "@/lib/site";

/**
 * The default social card.
 *
 * Generated by Next's own image renderer, which ships with the framework, so
 * there is no design tool in the pipeline and no image to keep in sync with the
 * content by hand.
 */
export const runtime = "nodejs";
export const alt = `${SITE.name}, ${SITE.tagline}`;
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function Image() {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        background: "#0a0b0d",
        padding: "72px",
        fontFamily: "sans-serif",
      }}
    >
      <div style={{ display: "flex", alignItems: "baseline", gap: "2px", fontSize: 34 }}>
        <span style={{ color: "#e2ab4e", fontWeight: 700 }}>0x</span>
        <span style={{ color: "#e9ecf1", fontWeight: 700 }}>Semantic</span>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
        {/* Two stacked lines rather than one with a break. The image renderer
            requires an explicit display on any element with more than one
            child, and a line break counts as one. */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{ fontSize: 68, color: "#e9ecf1", lineHeight: 1.15, letterSpacing: "-0.02em" }}
          >
            Systems built to be understood,
          </div>
          <div
            style={{ fontSize: 68, color: "#e9ecf1", lineHeight: 1.15, letterSpacing: "-0.02em" }}
          >
            not just shipped.
          </div>
        </div>
        <div style={{ fontSize: 28, color: "#9ba3b0" }}>{SITE.tagline}</div>
      </div>

      <div
        style={{
          display: "flex",
          fontSize: 22,
          color: "#626a77",
          letterSpacing: "0.14em",
          textTransform: "uppercase",
        }}
      >
        Classic and 0xAsk
      </div>
    </div>,
    size,
  );
}
